### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by imSunnyk** [jj008/Digital_Voting#1]
How do I run this project?

**Comment by jj008** [comment]
Download the project
Open cmd and go in the folder where there is manage.py file

Run this command
python manage.py runserver

**Comment by imSunnyk** [comment]
But before that dependecies have to be installed.... isn't it....

So what about that please?

**Comment by jj008** [comment]
Following are the libraries to be installed in the image

**Comment by jj008** [comment]
Following are the libraries to be installed
I am attaching the image of libraries

![IMG_20200401_123319_1](https://user-images.githubusercontent.com/50169669/89409645-05003580-d740-11ea-8061-132b6e7bded4.jpg)

**Comment by imSunnyk** [comment]
I changed db setting to db.sqlite3 but 
I am not able to register , its not taking voterid after click in regiter voter id same page apppears but its not registered
![Screenshot from 2020-09-13 14-29-26](https://user-images.githubusercontent.com/63893843/93014362-228dae00-f5ce-11ea-9535-df69d7de25eb.png)

and I tried creating new user through admin settings but not able to login in 
![Screenshot from 2020-09-13 14-28-37](https://user-images.githubusercontent.com/63893843/93014380-43560380-f5ce-11ea-968b-180663402039.png)

**Comment by jj008** [comment]
First add the voter details by login into admin account under the add voter
section

Then you have to register and a otp will come on the number which the admin
has entered in the voter details(add voter section)

Any help mail me on jaydeepjadeja896@gmail.com

**Comment by jj008** [comment]
First add the voter details by login into admin account under the add voter section

Then you have to register and a otp will come on the number which the admin has entered in the voter details(add voter section).

**Comment by jj008** [comment]
For any help mail me at jaydeepjadeja896@gmail.com

**Comment by Manavjawrani** [comment]
What is id and password for admin
