### ISSUE TITLE
Tutorial on how to install/setup the project

### ISSUE THREAD

**Issue by Kabari** [jj008/Digital_Voting#10]
Hello there,
Please I am finding it hard setting up the project and installing packages, and also running the project locally.
Please can you update your readme on the recent process on how to setup the project. Thanks in advance

**Comment by angelpriya27** [comment]
first of al delete all the packages of python like setuptools, django. After uninstall all restart your pc and install python 3.9.
after installing python 3.9 install th package which is mention in readme file and yur project will be going to run.
in dango admin you have to create new  admin in django and same login credientals used in createsuper user. after that you will be login admin page of voter.

**Comment by Kabari** [comment]
Thank you for the direction....I have spun it up and its working, I have created a superuser and logged in to Django administration page and added my details, but I can't seem to login to the admin dashboard. This is the homepage:

![Screenshot (4)](https://user-images.githubusercontent.com/66024861/213418713-f1af8cb3-19cc-41c2-8a3f-580c686b5a57.png)

Then when I input my login details and then login, I get this text under the forgot password link

![Screenshot (5)](https://user-images.githubusercontent.com/66024861/213425621-312fa439-90a6-4c3c-852a-a51066255492.png)

Then when I try to login with the superuser account I created, I get this error:

![Screenshot (6)](https://user-images.githubusercontent.com/66024861/213425803-7aff04a3-b862-471b-bf26-18b2b7df5d5b.png)

How do I generate a voter ID to register on the platform?

**Comment by angelpriya27** [comment]
do one thing open your django admin.after login in django admin create ec
admin and fill details.
after that create superuser in terminal with same details when  you create
ec admin..
after that username and password you will enter in this admin

**Comment by codingaslu** [comment]
i'm facing the same prblm

**Comment by jj008** [comment]
Please check the latest code and steps-readme.md
