### ISSUE TITLE
i dont get how this work can u explain properly

### ISSUE THREAD

**Issue by ramcharan0** [jj008/Digital_Voting#11]
![Screenshot (30)](https://user-images.githubusercontent.com/124513193/219848584-6c607d4c-0700-4947-8293-697e821e7843.png)
if i select telangana i get north goa and south goa option and i cant select Assembly Constituency in any state 
![Screenshot (31)](https://user-images.githubusercontent.com/124513193/219848666-50a61a67-9408-4311-95c1-2f0762d8e1a0.png)
can u please explain how to use ur DIgital_voting  system properly .
please try to make a simple step-by-step video or a blog i really appericate ur work..
please consider doing it

**Comment by angelpriya27** [comment]
ok i will tell you that .
I only entry the state of gujrat . you can add more state  in which is in
this code . you will find that when you check every code.

**Comment by ramcharan0** [comment]
so will the sms and face recognition works?? if i add the entry for the state ?? 
And what is the problem with the  Assembly Constituency issue.

**Comment by angelpriya27** [comment]
for sms u have to put your sms key from the web seite of 2 factor or
something like this website.
and raed the readme file where mention that u have to put your own sms api
key.
So first rad this

**Comment by ramcharan0** [comment]
sorry but i have another question for you
Iam getting this error(server error 500) while regestering voter

Uploading regprob.mp4…


It is generating the Trainingimages but voter is not getting regestered 
![Screenshot (34)](https://user-images.githubusercontent.com/124513193/220347233-f6aa6545-4421-4fca-bfaa-c9df988a0a96.png)


And can u please send me the ER model digram i think u probably created one while ur creating this project . can u please share it. i really apperciate ur efforts to help others, iam sure it will be the last request form me....
Thank you very much

**Comment by jj008** [comment]
Please check the latest code and steps-readme.md
