### ISSUE TITLE
getting error due to Trainner.yml file .

### ISSUE THREAD

**Issue by KishaN2202** [jj008/Digital_Voting#12]
Hello there I am trying to run this project . But facing one problem ,after going to election and add video for voting i am getting  following error 
File "C:\Users\Admin\Desktop\djnago\Digital_Voting-master\voter\views.py" in vote
  257.             rec.read(BASE_DIR+"/TrainingImageLabel/Trainner.yml")

Exception Type: error at /voter/vote
Exception Value: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-qjdp5db9\opencv_contrib\modules\face\src\facerec.cpp:61: error: (-2:Unspecified error) File can't be opened for reading! in function 'cv::face::FaceRecognizer::read'
.(Is this error due to trainner.yml ,if yes i am not able to find this file in the project it seems to missing )

**Comment by KishaN2202** [comment]
![Screenshot (1699)](https://user-images.githubusercontent.com/88761070/233805248-9348899f-0d73-4374-9b0b-aa2fb9d9d79f.png)
![Uploading Screenshot (1701).png…]()

**Comment by angelpriya27** [comment]
bro the video part is not working in this project so just removed the video
part from his project.

**Comment by KishaN2202** [comment]
Then how should I  recognise the faces  ??

**Comment by angelpriya27** [comment]
YOU HAVE TO UPDATE THE OPEN CV WITH LATEST AND IMPLEMENT IN IT

**Comment by Adithya-5134** [comment]
Bro have you finished the open cv part

**Comment by Adithya-5134** [comment]
Bro do you have the updated open cv code.... if you have pls contact me ecadithya12@gmail.com

**Comment by Adithya-5134** [comment]
@kishan2002  @angelpriya have you finished the full project with face recognition

**Comment by Adithya-5134** [comment]
Send me any voting system with face recognition source code....and it should work properly without any error

**Comment by angelpriya27** [comment]
bro i dont have . you have to find these things.

**Comment by KishaN2202** [comment]
Hello @Adithya-5134  ,  I removed that openCV part from this project and made it working. also, I have tried my own openCV script with it but it is not working :(   .  I agree with @angelpriya27  that you should find other project , because to remove openCV script from this project requires lot of changes.

**Comment by Adithya-5134** [comment]
Kishan bro send me the code without cv

**Comment by Adithya-5134** [comment]
KishaN2202

**Comment by Adithya-5134** [comment]
@KishaN2202 bro send the code as soon as possible... tomorrow final review
..pls help bro

**Comment by Adithya-5134** [comment]
Bro if you have voting system with face recognition pls send bro

**Comment by jj008** [comment]
Please check the latest code and steps-readme.md
