### ISSUE TITLE
cant select state please help me 

### ISSUE THREAD

**Issue by Cyborgreddy** [jj008/Digital_Voting#16]

**Comment by Cyborgreddy** [comment]
![Screenshot (41)](https://github.com/jj008/Digital_Voting/assets/125900743/583b1459-1436-4426-82f4-913c30e69c30)

**Comment by Cyborgreddy** [comment]
please help me with the above issue

**Comment by codingaslu** [comment]
I'm not able to login to admin.how did you solved 

![Screenshot (99)](https://github.com/jj008/Digital_Voting/assets/77477585/1414f84e-bf9c-4e77-b5bd-3a3d13362991)
![Screenshot (100)](https://github.com/jj008/Digital_Voting/assets/77477585/efc6f27a-81a1-4173-918a-93ee5651dd64)

**Comment by jj008** [comment]
Please check the latest code and steps-readme.md
