### ISSUE TITLE
Anyone need help to run this project

### ISSUE THREAD

**Issue by Adithya-5134** [jj008/Digital_Voting#17]
Contact me at insta....My id : adithya_1206

**Comment by Adithya-5134** [comment]
But i made it work

**Comment by angelpriya27** [comment]
really it working fine?.I cant believe this bro.if you done that hats off
to you

**Comment by Adithya-5134** [comment]
Yes...the major issue is in the open cv... with the help of my frnds...i made it

**Comment by prince-jagaban** [comment]
please i need help in running the project, how can i contact you? i don't mind paying for your time @Adithya-5134

**Comment by jj008** [comment]
Please check the latest code and steps-readme.md
