### ISSUE TITLE
eletion voting

### ISSUE THREAD

**Issue by prince-jagaban** [jj008/Digital_Voting#18]
after I enter the email-otp, it brings this. any idea on how to reslove it 
![Screenshot 2023-10-16 090749](https://github.com/jj008/Digital_Voting/assets/92142405/cbc0c45d-c9ec-49ae-9eb2-497b6f5810ed)

**Comment by Adithya-5134** [comment]
Contact me at insta

**Comment by jj008** [comment]
Please check the latest code and steps-readme.md
