### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Prashanthg300** [jj008/Digital_Voting#21]
after creating Ec_admins, when trying to login as admin it is raising an error as page not found

![Screenshot 2023-11-18 222121](https://github.com/jj008/Digital_Voting/assets/74718400/7aafb104-60df-4490-9925-b145d57537d7)

**Comment by Adithya-5134** [comment]
Need help contact me in insta

**Comment by jj008** [comment]
@Prashanthg300, can you try with the latest code
