### ISSUE TITLE
Request for Final project report 

### ISSUE THREAD

**Issue by Prashanthg300** [jj008/Digital_Voting#26]
Hello Jaydeepsinh Jadeja,

I hope this message finds you well. I am reaching out to kindly request if you could provide me with a copy of the project report for the Digital Voting project, if you have it available.

As I am currently working on a related project and believe that your insights from the Digital Voting project could be extremely valuable in informing our approach and decision-making process. Your expertise in this area is highly respected, and I am confident that your project report would provide valuable insights and guidance.

If it's convenient for you, could you please share the project report with me at your earliest convenience? Your assistance in this matter would be greatly appreciated.

**Comment by akhil-vj** [comment]
> Hello Jaydeepsinh Jadeja,
> had you completed your project

**Comment by jj008** [comment]
Hi @Prashanthg300,

Project report is not available with me, you can refer to the published research paper
https://www.irjmets.com/uploadedfiles/paper/volume2/issue_6_june_2020/1518/1628083038.pdf
