### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Manavjawrani** [jj008/Digital_Voting#4]
What is id and password for admin

**Comment by Skye10da** [comment]
are you able to setup the digital voting ?

**Comment by Manavjawrani** [comment]
Yes site is working but get login into admin , since credentials are not there, can pls help

**Comment by Manavjawrani** [comment]
Can we have a short Google meet ? 
This my number - 9545334179

**Comment by jj008** [comment]
Hi @Manavjawrani ,
you have to makemigrations of the models into database and then run the command 
`python manage.py createsuperuser`
and you can give new username and password

I will ping you on your number and we can have a call

**Comment by Manavjawrani** [comment]
Yes pls ping me we will have a call and sort it out

**Comment by Skye10da** [comment]
can you help me with the setup on localhost

**Comment by Manavjawrani** [comment]
Yes, I can.

**Comment by Skye10da** [comment]
lets talk here meet.google.com/xga-jjfs-thu

**Comment by Manavjawrani** [comment]
Can we meet by sat

**Comment by Skye10da** [comment]
I have fixed the problem and run the app successful, thanks
