### ISSUE TITLE
User matching query does not exist 

### ISSUE THREAD

**Issue by Skye10da** [jj008/Digital_Voting#6]
Does NotExist at /forgot password

User matching query does not exist. Request Method:

POST

Request URL: http://127.0.0.1:8000/forgot password

Django Version: 4.1

Exception Type: DoesNotExist

Exception Value: User watching query does not exist.

Exception Location:

CUsers Skye\AppData\Local\Programs\Python\Python310ibisite-packages/djangoldbimodelsiquery.py line 65 Raised during: home views forgot password

Python Executable: C Users Skye\AppData\Local\Programs\Python Python310 python.exe

**Comment by Skye10da** [comment]
The same thing happened on admin too

**Comment by Skye10da** [comment]
Does NotExist at /EC_Admin/adminhome

EC Admins matching query does not exist.

Request Method: GET

http://127.0.0.1:8000/EC Admin/adminhome

Request URL: Django Version: 41

Exception Type: DoesNotExist

Exception Value: Admins matching query does not exist.

Exception Location:

CUsers Skye\AppData\Local Programs Python Python310bsite-packages/django/db/models/query.py, line 6

Raised during: EC Admin views.adminhome.

Python Executable: C:\Users\Skye:AppData\Local Programs Python Python310 python.exe. Python Version: 310

**Comment by jj008** [comment]
pull the latest code added exception for this situation,
first add details of superuser in EC_Admins table by login in django administration page,
